name: Release A New Version

on:
    push:
        tags:
            - "*"

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - run: bun install

            - run: bun run build

            - name: Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
                  draft: false
                  prerelease: false
